name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      id: semver
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        bump_each_commit_patch_pattern: "fix:"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"


    - name: Export version
      run: echo "NEW_VERSION=${{ steps.semver.outputs.version }}" >> $GITHUB_ENV


    - name: Show calculated version
      run: echo "Version = $NEW_VERSION"


    - name: Docker Login
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin


    - name: Build Docker Image
      run: |
        docker build \
          -t anderortiz/docker-graphql:$NEW_VERSION \
          -t anderortiz/docker-graphql:latest .


    - name: Push Docker Image
      if: github.ref == 'refs/heads/master'
      run: |
        docker push anderortiz/docker-graphql:$NEW_VERSION
        docker push anderortiz/docker-graphql:latest


    - name: Build & Push Multi-Arch Image
      uses: docker/build-push-action@v6
      if: github.ref == 'refs/heads/master'
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          anderortiz/docker-graphql:$NEW_VERSION
          anderortiz/docker-graphql:latest